services:
  ts_db:
    container_name: ts_db
    image: typesense/typesense:30.1
    env_file:
      - .env.docker
    ports:
      - "${TS_PORT}:${TS_PORT}"
    volumes:
      - ${TS_DATA_DIR}:/data
    command: ["--data-dir", "/data", "--api-key=${TS_API_KEY}", "--enable-cors"]

  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mcp:
    container_name: mcp
    build: ./mcp
    env_file:
      - .env.docker
    ports:
      - "8001:8001"
    depends_on:
      - ts_db

  api:
    container_name: api
    build: ./api
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./sample_transcript:/app/sample_transcript
    depends_on:
      ts_db:
        condition: service_started
      mcp:
        condition: service_started
      mysql:
        condition: service_healthy
